name: Deploy Vue.js to VPS

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Node and dependencies
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies and build
      run: |
        npm install
        npm run build

    - name: Deploy to VPS via SSH
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "dist/*"
        target: ${{ secrets.VPS_PATH }}
